# Generated by Django 4.2.6 on 2023-10-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_news_date_alter_news_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='path',
            field=models.URLField(verbose_name='Путь в виде ссылки'),
        ),
    ]
