# Generated by Django 4.2.6 on 2023-10-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_news_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='url',
        ),
        migrations.AlterField(
            model_name='news',
            name='path',
            field=models.FilePathField(verbose_name='Название картинки'),
        ),
    ]
