# Generated by Django 4.2.6 on 2023-10-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_news_url_alter_news_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='path',
            field=models.URLField(verbose_name='Путь в виде ссылки'),
        ),
    ]
