# Generated by Django 4.2.6 on 2023-10-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_news_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='path',
            field=models.FileField(default='default.jpeg', upload_to='', verbose_name='Путь в виде ссылки'),
        ),
    ]
