# Generated by Django 4.2.6 on 2023-10-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_news_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.PositiveSmallIntegerField()),
                ('monday_lessons', models.CharField(blank=True, max_length=200, null=True)),
                ('tuesday_lessons', models.CharField(blank=True, max_length=200, null=True)),
                ('wednesday_lessons', models.CharField(blank=True, max_length=200, null=True)),
                ('thursday_lessons', models.CharField(blank=True, max_length=200, null=True)),
                ('friday_lessons', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'unique_together': {('class_number',)},
            },
        ),
    ]
