# Generated by Django 4.2.6 on 2023-10-24 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_weeklyschedule'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeeklySchedule',
            new_name='Lessons',
        ),
    ]
