# Generated by Django 4.2.6 on 2023-11-07 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_message11_delete_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message11',
        ),
    ]
